name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Debug

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install conan
        run: pip install conan

      - name: Install ninja
        run: sudo apt-get update && sudo apt-get install -y build.ninja

      - name: Cache (NDK)
        uses: actions/cache@v2
        with:
          path: ${ANDROID_HOME}/ndk/25.1.8937393
          key: ndk-cache

      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install 'ndk;25.1.8937393'

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}\build -GNinja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_ARCH_ABI="arm64-v8a" -DCMAKE_ANDROID_NDK=${ANDROID_HOME}/ndk/25.1.8937393 -DCMAKE_SYSTEM_VERSION=24 -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang

      - name: Build
        run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}
